data:
  input_file: ''
  output_dir: ''
  features:
  target:
model:
  sequence_length: 24
  lstm_layers:
    - units: 128
      dropout: 0.2
    - units: 64
      dropout: 0.2
  dense_layers:
    - units: 64
      activation: relu
  output_units: 1
  output_activation: linear

training:
  loss: mse
  optimizer: adam
  learning_rate: 0.001
  epochs: 100
  batch_size: 64
  validation_split: 0.25
  callbacks:
    early_stopping:
      monitor: val_loss
      patience: 10
      restore_best_weights: true
